### ISSUE TITLE
Unmarshalling bug for primitive fields

### ISSUE THREAD

**Issue by kerbymart** [textquo/twist#39]
INFO] Caused by: java.lang.IllegalArgumentException: Can not set boolean field com.gwt.app.client.local.entity.ThingItem.privateFlag to null value
[INFO] 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164)
[INFO] 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168)
[INFO] 	at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:80)
[INFO] 	at java.lang.reflect.Field.set(Field.java:741)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime$12.run(Runtime.java:257)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.verifyAndRun(Runtime.java:374)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.set(Runtime.java:254)
[INFO] 	at com.textquo.twist.gae.GaeUnmarshaller.setFieldValue(GaeUnmarshaller.java:95)
[INFO] 	at com.textquo.twist.gae.GaeUnmarshaller.doUnmarshall(GaeUnmarshaller.java:252)
[INFO] 	at com.textquo.twist.gae.GaeUnmarshaller.unmarshall(GaeUnmarshaller.java:72)
[INFO] 	at com.textquo.twist.types.Find.asList(Find.java:256)
[INFO] 	at com.gwt.app.server.resource.gae.GaeThingsServerResource.listThings(GaeThingsServerResource.java:18)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:115)
[INFO] 	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:524)
[INFO] 	... 74 more
[INFO]

**Comment by kerbymart** [comment]
fixed: https://github.com/textquo/twist/commit/28f7c8319339a38e696853a18fc42e3a2fef48f7
